name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}] # Har kuni Toshkent vaqti bilan 21:00 da ishlaydi
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🦑 General
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.TOKEN }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_languages: yes
          # HTML/CSS ni o'chirib qo'yish orqali JS/TS/Python statistikaningiz aniqroq ko'rinadi
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, shell, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 4
          plugin_topics: yes
          plugin_topics_mode: icons

      - name: 🦑 Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_achievements: yes
          plugin_achievements_display: compact
